[package]
name = "blurp"
version = "0.1.0"
authors = ["Stefan_Karlsson <gittest@k-son.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
